### ISSUE TITLE
Unable to install via pip

### ISSUE THREAD

**Issue by ryangallen** [kpodl/pytractor#5]
```
$ pip install pytractor
Collecting pytractor
  Using cached pytractor-0.0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/wn/xtj5g99d04b6np9lbym_nbpw0000gn/T/pip-build-e0q4pvcm/pytractor/setup.py", line 27, in <module>
        with open(path.join(here, 'DESCRIPTION.rst'), encoding='utf-8') as f:
      File "/Users/ryanallen/.virtualenvs/sdj/bin/../lib/python3.4/codecs.py", line 896, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/wn/xtj5g99d04b6np9lbym_nbpw0000gn/T/pip-build-e0q4pvcm/pytractor/DESCRIPTION.rst'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/wn/xtj5g99d04b6np9lbym_nbpw0000gn/T/pip-build-e0q4pvcm/pytractor 
```
Is there support for Python 3?

**Comment by kpodl** [comment]
Thanks for your feedback! This is indeed a bug. And a particular irritating one, because I thought I had tested installation via pip.

As for python 3 support: Currently pytractor will not work with Python 3. I mostly still work with Python 2.7 so this is not a high priority for me.
Of course, Python 3 compatibility is a must have for the future.
